version: "3"
services:
  db:
    image: mysql:latest
    container_name: baloncesto-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: baloncesto
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave
    ports:
    - "3309:3306"
    restart: always
    volumes:
    - ./db:/docker-entrypoint-initdb.d

  web:
    image: tomcat:latest
    restart: on-failure
    container_name: baloncesto-web
    environment:
      DATABASE_HOST: "jdbc:mysql://db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: baloncesto
      DATABASE_USER: usuario
      DATABASE_PASS: clave
    ports:
    - "8081:8080"
    volumes:
     - ./target:/usr/local/tomcat/webapps
    links:
      - db:baloncesto
    depends_on:
      - db
